apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: gpm-poc
data:
  enabled_plugins: |
      [rabbitmq_management,rabbitmq_peer_discovery_k8s].

  rabbitmq.conf: |
      ## Clustering
      cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
      cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
      cluster_formation.k8s.address_type = hostname
      cluster_formation.node_cleanup.interval = 10
      cluster_formation.node_cleanup.only_log_warning = false
      cluster_partition_handling = autoheal
      ## queue master locator
      queue_master_locator=min-masters
      ## enable guest user
      loopback_users.guest = false
      ## SSL configuration
      listeners.ssl.default = 5671
      ssl_options.cacertfile = /etc/certs/cacert.pem
      ssl_options.certfile = /etc/certs/cert.pem
      ssl_options.keyfile = /etc/certs/key.pem
      ssl_options.verify = verify_peer
      ssl_options.fail_if_no_peer_cert = false
