apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: gpm-poc
spec:
  clusterIP: None
  ports:
    - name: http
      port: 15672
    - name: amqp
      port: 5672
  selector:
    app: rabbitmq
