apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq-amqp
  namespace: gpm-poc
spec:
  ports:
    - name: amqp
      nodePort: 30672
      port: 30672
      protocol: TCP
      targetPort: 5672
    - name: amqps
      nodePort: 30671
      port: 30671
      protocol: TCP
      targetPort: 5671
  selector:
    app: rabbitmq
  type: LoadBalancer
---
