apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq-amqp
  namespace: gpm-poc
spec:
  ports:
    - name: amqp
      nodePort: 30672
      port: 5672
      protocol: TCP
      targetPort: 5672
  selector:
    app: rabbitmq
  type: NodePort
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq-amqps
  namespace: gpm-poc
spec:
  ports:
    - name: amqp
      nodePort: 30671
      port: 5671
      protocol: TCP
      targetPort: 5671
  selector:
    app: rabbitmq
  type: NodePort
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq-mgmt
  namespace: gpm-poc
spec:
  ports:
    - name: http
      nodePort: 31672
      port: 15672
      protocol: TCP
      targetPort: 15672
  selector:
    app: rabbitmq
  type: NodePort
---
